name: Docker Build Images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  PLATFORMS: 'linux/amd64,linux/arm64'
  IMAGE_NAME: 'easypi/scrapyd'
  SCRAPYD_VERSION: '1.5.0'
  SCRAPY_VERSION: '2.11.2'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            SCRAPYD_VERSION=${{ env.SCRAPYD_VERSION }}
            SCRAPY_VERSION=${{ env.SCRAPY_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.SCRAPYD_VERSION }}-${{ env.SCRAPY_VERSION }}
            ${{ env.IMAGE_NAME }}:latest
          # ghcr.io/${{ env.IMAGE_NAME }}:${{ env.SCRAPYD_VERSION }}-${{ env.SCRAPY_VERSION }}
          # ghcr.io/${{ env.IMAGE_NAME }}:latest
          push: true

      - if: ${{ always() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: github
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "title": "${{ github.repository }}",
                  "title_link": "https://github.com/${{ github.repository }}",
                  "text": "docker build image result",
                  "fields": [
                    {
                      "title": "Image",
                      "value": "<https://hub.docker.com/r/${{ env.IMAGE_NAME }}|${{ env.IMAGE_NAME }}>",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "${{ job.status }}",
                      "short": true
                    }
                  ],
                  "footer": "Github Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
