name: Docker Build Images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          tags: |
            easypi/scrapyd:latest
            ghcr.io/easypi/scrapyd:latest
          push: true

      - uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: github
          slack-message: 'docker build "scrapyd:latest" ok'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
